In [1]:
import pandas as pd
df=pd.read_csv("train.csv")
df.head()

,id,gender,s11,s12,s13,s16,s17,s18,s48,s52,...,n7,n8,n9,n10,n11,n12,n13,n14,n15,label
0,b'gAAAAABinOicS09vrmgh0_JyEHihI13ptO0rCyHP7l76...,M,Y,N,1,D,D,B,0,1,...,-9.126056,1.732291,3.698504,4.804517,1.544484,0,0,0.631220,5,0
1,b'gAAAAABinOiWGC1WhR6WYP0DA5ssGv9rIekrWUwCdJ8F...,M,Y,Y,1,D,D,B,1,1,...,-9.098287,1.505885,6.791357,6.110416,1.712354,0,0,0.392746,3,1
2,b'gAAAAABinOibTcOBFIVeA4nVF3FuFz_QX3ZlPPFc21gS...,M,Y,Y,1,D,D,B,0,1,...,-9.234894,1.503828,4.109685,3.953226,1.804260,0,0,0.222537,2,0
3,b'gAAAAABinOig-g3-Q1ggjlMhfUSdn21Aj5yVVeVvXbis...,F,Y,Y,1,D,D,B,0,1,...,-9.378025,1.485863,7.265876,4.559419,1.537645,0,0,0.154409,4,0
4,b'gAAAAABinOiXdoaNUzihOSbyY1tjWtd5EgMaXkkvH6SV...,M,N,Y,1,B,D,D,1,l,...,-9.261962,1.619210,3.737647,4.052003,1.637831,0,1,0.737560,1,0

In [2]:
from sklearn.preprocessing import LabelEncoder
le_gender=LabelEncoder()
le_s11=LabelEncoder()
le_s12=LabelEncoder()
le_s16=LabelEncoder()
le_s17=LabelEncoder()
le_s18=LabelEncoder()
le_s48=LabelEncoder()
le_s52=LabelEncoder()
le_s54=LabelEncoder()
le_s55=LabelEncoder()
le_s58=LabelEncoder()
le_s69=LabelEncoder()
le_s70=LabelEncoder()
le_s71=LabelEncoder()
le_s53=LabelEncoder()
le_s56=LabelEncoder()
le_s57=LabelEncoder()
le_s59=LabelEncoder()
df['s11_n']=le_gender.fit_transform(df['gender'])
df['S12_n']=le_s12.fit_transform(df['s12'])
df['s16_n']=le_s16.fit_transform(df['s16'])
df['s17_n']=le_s17.fit_transform(df['s17'])
df['s18_n']=le_s18.fit_transform(df['s18'])
df['s48_n']=le_s48.fit_transform(df['s48'])
df['s52_n']=le_s52.fit_transform(df['s52'])
for c in  df.columns:
    df[c].fillna('No', inplace = True)
df['s53_n']=le_s53.fit_transform(df['s53'])
df['s54_n']=le_s54.fit_transform(df['s54'])
df['s55_n']=le_s55.fit_transform(df['s55'])
df['s56_n']=le_s56.fit_transform(df['s56'])
df['s57_n']=le_s57.fit_transform(df['s57'])
df['s58_n']=le_s58.fit_transform(df['s58'])
df['s59_n']=le_s59.fit_transform(df['s59'])
df['s69_n']=le_s69.fit_transform(df['s69'])
df['s70_n']=le_s70.fit_transform(df['s70'])
df['s71_n']=le_s71.fit_transform(df['s71'])

In [3]:
target=df['label']
input_n=df.drop(['id','gender','s11','s12','s16','s17','s18','s52','s53','s54','s55','s56','s57','s58','s59','s69','s70','s71'],axis='columns')

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(input_n,target,test_size=0.30)
from sklearn.ensemble import RandomForestClassifier 
model=RandomForestClassifier(n_estimators=20)

In [8]:
X_train

,s13,s48,n1,n2,n3,n4,n5,n6,n7,n8,...,s53_n,s54_n,s55_n,s56_n,s57_n,s58_n,s59_n,s69_n,s70_n,s71_n
1599,1,0,11.729128,1.446877,3,2.055995,-32.773849,0.018424,-9.172175,2.056691,...,1,3,6,0,0,1,0,3,3,1
2336,1,0,9.260782,1.471994,4,2.388253,-32.775454,0.004469,-9.221682,1.487807,...,1,3,6,0,0,1,0,3,3,1
5395,1,0,11.436406,1.872848,2,2.822209,-32.858171,0.017797,-9.004704,1.510420,...,1,3,6,0,0,1,0,2,3,2
5640,1,0,12.545012,1.709758,7,2.391581,-32.847890,0.015978,-8.836602,1.734433,...,1,3,6,0,0,1,0,2,3,1
10864,1,1,16.411473,1.822008,8,8.287917,-33.053397,0.005442,-8.705839,1.869912,...,1,3,6,0,0,1,0,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9419,1,0,5.584587,0.912680,6,2.818650,-32.397327,0.015477,-9.223951,1.512815,...,1,3,6,0,0,1,0,2,3,1
19229,1,1,9.762257,1.492326,2,8.060053,-33.067341,0.013139,-9.131286,1.491512,...,1,3,6,0,0,1,0,3,1,1
12966,1,1,16.866920,2.443568,3,6.809440,-32.350813,0.025244,-9.168290,2.092319,...,1,3,6,0,0,1,0,3,2,3
9945,1,1,5.068168,0.800536,6,8.385206,-33.109757,0.004546,-8.729013,1.509089,...,1,3,6,0,0,1,0,2,3,1
26440,1,1,14.724420,2.135367,7,2.376267,-32.448883,0.017920,-8.941270,1.506745,...,1,3,6,0,0,1,0,2,1,1

In [6]:
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=20)

In [7]:
model.score(X_test,y_test)

1.0

In [9]:
X_test

,s13,s48,n1,n2,n3,n4,n5,n6,n7,n8,...,s53_n,s54_n,s55_n,s56_n,s57_n,s58_n,s59_n,s69_n,s70_n,s71_n
10959,1,0,11.681881,2.015653,1,2.478034,-32.893095,0.016606,-9.225650,1.715791,...,1,3,6,0,0,1,0,2,3,1
5241,1,1,15.897762,2.477731,8,6.895037,-32.453098,0.006870,-8.711083,1.865587,...,1,3,6,0,0,1,0,2,3,1
23340,1,0,10.332325,2.321104,2,6.876742,-32.330632,0.026084,-9.091599,2.032240,...,0,3,6,0,0,1,0,2,3,1
841,1,0,5.256503,0.876694,3,3.578515,-32.643917,0.021204,-9.364293,1.428157,...,1,3,6,0,0,1,0,3,3,1
894,1,0,16.111814,2.511538,3,8.153685,-32.321637,0.026423,-8.862293,2.063082,...,1,3,6,0,0,1,0,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,1,1,17.773962,2.304945,8,7.183346,-32.577152,0.008863,-8.758602,1.885323,...,1,3,6,0,0,1,0,2,3,1
9655,1,1,19.126944,1.424149,2,8.357227,-32.641352,0.023863,-9.048030,1.869275,...,1,3,6,0,0,1,0,2,2,1
16771,1,0,6.704500,3.010004,1,2.126314,-32.452656,0.026272,-9.199523,1.798855,...,1,3,6,0,0,1,0,1,1,1
645,1,1,12.693218,0.576292,3,2.506100,-32.513214,0.016327,-9.431617,1.503827,...,1,3,6,0,0,1,0,3,1,1
16742,1,1,7.307314,1.182248,3,5.808354,-32.394907,0.013194,-9.269038,1.472822,...,1,7,6,0,0,0,0,2,3,1

In [10]:
input_n

,s13,s48,n1,n2,n3,n4,n5,n6,n7,n8,...,s53_n,s54_n,s55_n,s56_n,s57_n,s58_n,s59_n,s69_n,s70_n,s71_n
0,1,0,16.144666,1.989441,2,2.318385,-32.839277,0.017176,-9.126056,1.732291,...,1,3,8,0,0,1,0,2,3,1
1,1,1,7.144558,0.844866,3,6.197768,-32.576597,0.013857,-9.098287,1.505885,...,1,3,6,0,0,1,0,2,3,1
2,1,0,6.923236,1.042018,6,7.824401,-32.510544,0.013943,-9.234894,1.503828,...,1,3,6,0,0,1,0,2,3,1
3,1,0,5.749840,0.781439,2,8.256767,-32.398679,0.010387,-9.378025,1.485863,...,1,3,6,0,0,1,0,2,3,1
4,1,1,14.771959,1.248188,3,2.300011,-32.396746,0.016289,-9.261962,1.619210,...,1,3,6,0,0,1,0,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28317,1,0,16.375618,2.480253,7,4.693939,-33.086259,0.007216,-8.651173,1.877460,...,1,3,6,0,0,1,0,2,3,1
28318,1,0,14.746677,2.035971,6,7.939976,-32.775474,0.013369,-8.833046,1.559138,...,1,3,1,0,0,1,0,2,3,1
28319,1,0,13.429797,1.800562,3,7.763386,-32.575975,0.017782,-9.233722,1.455911,...,1,3,6,0,0,1,0,2,3,1
28320,1,1,16.094622,2.438280,8,6.942766,-32.577563,0.007324,-8.748941,2.074394,...,1,3,6,0,0,1,0,3,2,1
28321,1,1,7.058107,1.023172,3,5.942025,-32.848897,0.015928,-9.280950,1.490478,...,1,3,6,0,0,1,0,2,3,1